import React from "react";
import { Header } from "../Components/Header";
import {Footer} from "../Components/Footer.jsx"
export function SobreNosotros(){
    return(
        <div>
             <Header/>
             <div>
             <h1>Sobre nosotros</h1>
             <p>Lorem ipsum dolor sit amet. Et nihil possimus aut nihil voluptatum ea explicabo autem. Aut eligendi sunt ad dolorum consequatur aut tenetur blanditiis ex possimus ipsa 33 iste ipsa At tempora tempore sit odio obcaecati! Ea iste cupiditate ut ipsam neque non eligendi odit 33 dicta illum est enim delectus. Ex dolore nisi qui dicta eaque eos dignissimos tempora nam accusamus officiis est itaque enim. </p><p>Ex voluptatem rerum ut quisquam vitae aut assumenda voluptatem 33 sunt impedit in quisquam voluptas et atque odit est nesciunt illo. Est dolores quia qui minima placeat id omnis repudiandae sed iure consequuntur. Qui dolore tenetur et omnis mollitia est aliquam quidem. </p><p>Et esse possimus At deserunt earum qui accusantium expedita est eaque quaerat eum laudantium laborum aut molestiae voluptatem et consectetur eveniet. Non mollitia alias ab Quis culpa et excepturi delectus nam corrupti quia. Ut aperiam amet est perferendis accusantium et eligendi quia. </p>
             <p>Lorem ipsum dolor sit amet. Et nihil possimus aut nihil voluptatum ea explicabo autem. Aut eligendi sunt ad dolorum consequatur aut tenetur blanditiis ex possimus ipsa 33 iste ipsa At tempora tempore sit odio obcaecati! Ea iste cupiditate ut ipsam neque non eligendi odit 33 dicta illum est enim delectus. Ex dolore nisi qui dicta eaque eos dignissimos tempora nam accusamus officiis est itaque enim. </p><p>Ex voluptatem rerum ut quisquam vitae aut assumenda voluptatem 33 sunt impedit in quisquam voluptas et atque odit est nesciunt illo. Est dolores quia qui minima placeat id omnis repudiandae sed iure consequuntur. Qui dolore tenetur et omnis mollitia est aliquam quidem. </p><p>Et esse possimus At deserunt earum qui accusantium expedita est eaque quaerat eum laudantium laborum aut molestiae voluptatem et consectetur eveniet. Non mollitia alias ab Quis culpa et excepturi delectus nam corrupti quia. Ut aperiam amet est perferendis accusantium et eligendi quia. </p>
             <p>Lorem ipsum dolor sit amet. Et nihil possimus aut nihil voluptatum ea explicabo autem. Aut eligendi sunt ad dolorum consequatur aut tenetur blanditiis ex possimus ipsa 33 iste ipsa At tempora tempore sit odio obcaecati! Ea iste cupiditate ut ipsam neque non eligendi odit 33 dicta illum est enim delectus. Ex dolore nisi qui dicta eaque eos dignissimos tempora nam accusamus officiis est itaque enim. </p><p>Ex voluptatem rerum ut quisquam vitae aut assumenda voluptatem 33 sunt impedit in quisquam voluptas et atque odit est nesciunt illo. Est dolores quia qui minima placeat id omnis repudiandae sed iure consequuntur. Qui dolore tenetur et omnis mollitia est aliquam quidem. </p><p>Et esse possimus At deserunt earum qui accusantium expedita est eaque quaerat eum laudantium laborum aut molestiae voluptatem et consectetur eveniet. Non mollitia alias ab Quis culpa et excepturi delectus nam corrupti quia. Ut aperiam amet est perferendis accusantium et eligendi quia. </p>
             <p>Lorem ipsum dolor sit amet. Et nihil possimus aut nihil voluptatum ea explicabo autem. Aut eligendi sunt ad dolorum consequatur aut tenetur blanditiis ex possimus ipsa 33 iste ipsa At tempora tempore sit odio obcaecati! Ea iste cupiditate ut ipsam neque non eligendi odit 33 dicta illum est enim delectus. Ex dolore nisi qui dicta eaque eos dignissimos tempora nam accusamus officiis est itaque enim. </p><p>Ex voluptatem rerum ut quisquam vitae aut assumenda voluptatem 33 sunt impedit in quisquam voluptas et atque odit est nesciunt illo. Est dolores quia qui minima placeat id omnis repudiandae sed iure consequuntur. Qui dolore tenetur et omnis mollitia est aliquam quidem. </p><p>Et esse possimus At deserunt earum qui accusantium expedita est eaque quaerat eum laudantium laborum aut molestiae voluptatem et consectetur eveniet. Non mollitia alias ab Quis culpa et excepturi delectus nam corrupti quia. Ut aperiam amet est perferendis accusantium et eligendi quia. </p>
             <Footer/>
             </div>
             
        </div>
        
    )
}